services:
  beets:
    image: beets-mixonaut:latest
    container_name: beets-mixonaut
    user: 1000:1000
    network_mode: bridge
    ports:
      - "8337:8337"
    volumes:
      - /home/pipo/data/appdata/beets-xtractor-docker/config:/app/config
      - /home/pipo/data/appdata/beets-xtractor-docker/xtractor:/app/xtractor
      - /home/pipo/data/db/beets-xtractor:/app/db
      - /home/pipo/data/logs/beets-xtractor:/app/logs
      - /mnt/user/Musiques/Collection:/app/data
      - /mnt/user/Musiques/Atrier:/app/import
    environment:
      - HOME=/tmp
      #- PUID=pipo #nobody
      #- PGID=users #users
      - TZ=Europe/Paris
      - BEETSDIR=/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    entrypoint: ["/app/entrypoint.sh"]
    tty: true
