services:
  beets:
    image: u2pitchjami/beets-xtractor:latest
    container_name: beets-xtractor
    network_mode: bridge
    ports:
      - "8337:8337"
    volumes:
      - /home/pipo/beets-xtractor-docker/config:/app/config
      - /mnt/user/Musiques/Collection:/app/data
      - /mnt/user/Musiques/Atrier:/app/import
    environment:
      BEETSDIR: /app/config
    entrypoint: ["/app/entrypoint.sh"]
    tty: true
