services:
  beets:
    image: u2pitchjami/beets-xtractor:latest
    container_name: beets-xtractor
    user: 99:100
    network_mode: bridge
    ports:
      - "8337:8337"
    volumes:
      - /home/pipo/bin/beets-xtractor-docker/config:/app/config
      - /mnt/user/Musiques/Collection:/app/data
      - /mnt/user/Musiques/Atrier:/app/import
    environment:
      - HOME=/tmp
      #- PUID=pipo #nobody
      #- PGID=users #users
      - TZ=Europe/Paris
      - BEETSDIR=/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    entrypoint: ["/app/entrypoint.sh"]
    tty: true
