chromaprint:
  compute: 0
highlevel:
  compute: 1
  svm_models:
  - /app/config/svm_models/danceability.history
  - /app/config/svm_models/gender.history
  - /app/config/svm_models/genre_dortmund.history
  - /app/config/svm_models/genre_electronic.history
  - /app/config/svm_models/genre_rosamerica.history
  - /app/config/svm_models/genre_tzanetakis.history
  - /app/config/svm_models/ismir04_rhythm.history
  - /app/config/svm_models/mood_acoustic.history
  - /app/config/svm_models/mood_aggressive.history
  - /app/config/svm_models/mood_electronic.history
  - /app/config/svm_models/mood_happy.history
  - /app/config/svm_models/mood_sad.history
  - /app/config/svm_models/mood_party.history
  - /app/config/svm_models/mood_relaxed.history
  - /app/config/svm_models/timbre.history
  - /app/config/svm_models/tonal_atonal.history
  - /app/config/svm_models/voice_instrumental.history
  - /app/config/svm_models/moods_mirex.history
lowlevel:
  frameSize: 2048
  hopSize: 1024
outputFormat: json
outputFrames: 0
